ALTER TABLE student ADD CONSTRAINT age CHECK (age > 16)
ALTER TABLE student ADD CONSTRAINT name UNIQUE (name)
ALTER TABLE student ALTER COLUMN name SET not null
ALTER TABLE faculty ADD CONSTRAINT name_color_unique UNIQUE (name, colour)
ALTER TABLE student ALTER COLUMN age SET DEFAULT 20